//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatCrypto.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class i_key
    {
        public int ID { get; set; }
        public string key { get; set; }
    }
}
