//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatCrypto.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messsage
    {
        public int ID { get; set; }
        public Nullable<int> Sender_id { get; set; }
        public Nullable<int> Hash_id { get; set; }
        public Nullable<System.DateTime> Msg_time { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Hash Hash { get; set; }
    }
}
